"""Mirror of Active Directory: accounts, groups and direct membership, linked to employees.

Read-only: nothing is written to AD. employeeNumber is only checked; the stamping script is
generated by the «AD employeeNumber» report for an administrator to run.
"""

import hashlib
import json
import traceback
from collections import Counter, defaultdict

import frappe
from frappe.utils import cint, get_datetime, now_datetime

from access_registry.access_catalog.importer import save_changed, sync_child_table
from access_registry.access_catalog.linking import BY_AD, NameMatcher, ad_account_index
from access_registry.settings import get_settings
from access_registry.sync.engine import _format_messages, _switch_user

SAVEPOINT = "active_directory_sync"
DERIVED_VERSION = 1

UAC_DISABLED = 0x2
UAC_DONT_EXPIRE_PASSWORD = 0x10000
GROUP_SECURITY = 0x80000000
GROUP_SCOPES = {0x2: "Глобальная", 0x4: "Локальная в домене", 0x8: "Универсальная"}

VOLATILE = ("whenChanged", "lastLogonTimestamp", "lockoutTime")

BY_EMPLOYEE_NUMBER = "employeeNumber"
BY_NAME = "ФИО"


class ADGuardTripped(frappe.ValidationError):
	pass


# --------------------------------------------------------------------------- jobs


def scheduled_ad_sync():
	for domain in frappe.get_all("AD Domain", filters={"enabled": 1}, pluck="name"):
		enqueue(domain)


def job_id_for(domain: str) -> str:
	return f"active_directory_sync::{domain}"


def enqueue(domain: str):
	return frappe.enqueue(
		"access_registry.active_directory.sync.run_domain_sync",
		queue="long",
		timeout=get_settings().job_timeout,
		job_id=job_id_for(domain),
		deduplicate=True,
		domain=domain,
	)


def run_domain_sync(domain: str, commit: bool = True, fetch=None):
	"""Reads the directory and mirrors it in one transaction. Returns the Sync Log."""
	from access_registry.active_directory.ldap_client import fetch_directory

	settings = get_settings()
	log = frappe.get_doc(
		{"doctype": "Sync Log", "kind": "AD", "status": "В процессе", "started": now_datetime()}
	).insert(ignore_permissions=True)
	if commit:
		frappe.db.commit()
	stats, messages = {}, []
	previous_user = frappe.session.user
	_switch_user(settings.sync_user, messages)
	frappe.db.savepoint(SAVEPOINT)
	try:
		doc = frappe.get_doc("AD Domain", domain)
		data = (fetch or fetch_directory)(doc)
		importer = DomainImport(doc)
		stats = importer.run(data)
		messages += importer.warnings
		frappe.db.set_value("AD Domain", domain, "last_sync", now_datetime(), update_modified=False)
		status = "Успех"
	except ADGuardTripped as e:
		frappe.db.rollback(save_point=SAVEPOINT)
		status = "Остановлен предохранителем"
		messages.append(str(e))
	except Exception:
		messages.append(traceback.format_exc())
		frappe.db.rollback(save_point=SAVEPOINT)
		status = "Ошибка"
	finally:
		_switch_user(previous_user, None)
	log.reload()
	log.status = status
	log.finished = now_datetime()
	log.stats = json.dumps({"domain": domain, **stats}, ensure_ascii=False, indent=1, sort_keys=True)
	log.messages = _format_messages(messages)
	log.save(ignore_permissions=True)
	frappe.db.set_value(
		"AD Domain",
		domain,
		"last_status",
		f"{status} ({log.name}, {log.finished.strftime('%Y-%m-%d %H:%M')})",
		update_modified=False,
	)
	if commit:
		frappe.db.commit()
	return log


def load_directory_file(domain: str, path: str):
	"""Loads a saved directory (JSON of the fetch_directory shape) instead of reading LDAP.

	For a dev site and synthetic data (tools/generate_synthetic.py --ad):
	bench --site dev.localhost execute access_registry.active_directory.sync.load_directory_file \
		--kwargs "{'domain': 'CORP', 'path': '/path/to/ad/directory.json'}"
	"""
	frappe.only_for(("System Manager", "Registry Admin"))
	with open(path, encoding="utf-8") as fh:
		data = json.load(fh)
	log = run_domain_sync(domain, fetch=lambda _domain: data)
	return {"status": log.status, "log": log.name}


# --------------------------------------------------------------------------- import


def src_hash(payload) -> str:
	return hashlib.md5(
		json.dumps(payload, sort_keys=True, ensure_ascii=False, default=str).encode()
	).hexdigest()


def ou_of(dn: str | None) -> str:
	"""Parent container of a DN in a readable form: «Сотрудники / Москва»."""
	if not dn:
		return ""
	parts = [p for p in _split_dn(dn)[1:] if p.upper().startswith(("OU=", "CN="))]
	return " / ".join(p.split("=", 1)[1] for p in reversed(parts))


def _split_dn(dn: str) -> list:
	parts, current, escaped = [], "", False
	for ch in dn:
		if escaped:
			current += ch
			escaped = False
		elif ch == "\\":
			current += ch
			escaped = True
		elif ch == ",":
			parts.append(current.strip())
			current = ""
		else:
			current += ch
	if current:
		parts.append(current.strip())
	return parts


class DomainImport:
	def __init__(self, domain):
		self.domain = domain
		self.code = domain.name
		self.settings = get_settings()
		self.counters = Counter()
		self.warnings: list[str] = []

	def warn(self, text):
		self.warnings.append(f"Предупреждение: {text}")

	def key(self, guid):
		return f"{self.code}:{guid}"

	def run(self, data: dict) -> dict:
		users = [u for u in data.get("users") or [] if u.get("objectGUID")]
		groups = [g for g in data.get("groups") or [] if g.get("objectGUID")]
		self.check_guard(len(users))

		self.group_by_dn = {(g.get("distinguishedName") or "").lower(): g for g in groups}
		self.user_by_dn = {(u.get("distinguishedName") or "").lower(): u for u in users}
		self.persons = set(frappe.get_all("Person", pluck="name", limit_page_length=0))
		self.names = NameMatcher()

		self.import_groups(groups)
		self.group_names = dict(
			frappe.get_all(
				"AD Group", filters={"domain": self.code}, fields=["name", "group_name"], as_list=True
			)
		)
		self.volatile = {}
		for user in users:
			self.import_account(user)
		self.link_managers(users, groups)
		self.update_volatile()
		self.counters["accounts_missing"] = self.mark_missing(
			"AD Account", {self.key(u["objectGUID"]) for u in users}
		)
		self.counters["groups_missing"] = self.mark_missing(
			"AD Group", {self.key(g["objectGUID"]) for g in groups}
		)
		self.update_group_counts()
		self.counters["ib_users_relinked"] = relink_ib_users()

		self.counters["accounts"] = len(users)
		self.counters["groups"] = len(groups)
		return dict(self.counters)

	def check_guard(self, received):
		threshold = cint(self.settings.shrink_threshold_pct)
		actual = frappe.db.count("AD Account", {"domain": self.code, "missing_in_source": 0})
		if actual < cint(self.settings.guard_min_records):
			return
		if received < actual * (1 - threshold / 100):
			shrink = round(100 * (actual - received) / actual, 1)
			raise ADGuardTripped(
				f"Загрузка домена {self.code} остановлена предохранителем: учёток в AD {received}, "
				f"актуальных в реестре {actual} — сокращение на {shrink}%, допустимо не более {threshold}%. "
				f"Проверьте фильтр и OU в настройках домена. Если сокращение ожидаемое, временно поднимите "
				f"«Допустимое сокращение выгрузки, %» до {int(shrink) + 1} или выше."
			)

	def load(self, doctype, uid, payload_hash):
		if frappe.db.exists(doctype, uid):
			current = frappe.db.get_value(doctype, uid, ["src_hash", "missing_in_source"], as_dict=True)
			if current.src_hash == payload_hash and not current.missing_in_source:
				self.counters[f"{doctype}: без изменений"] += 1
				return None
			return frappe.get_doc(doctype, uid)
		doc = frappe.new_doc(doctype)
		doc.uid = uid
		return doc

	def save(self, doc):
		new = doc.is_new()
		if not save_changed(doc):
			self.counters[f"{doc.doctype}: без изменений"] += 1
		else:
			self.counters[f"{doc.doctype}: {'создано' if new else 'изменено'}"] += 1
		if doc.flags.cut_fields:
			self.warn(f"{doc.name}: слишком длинные значения обрезаны: {', '.join(doc.flags.cut_fields)}")

	def common(self, doc, row):
		doc.domain = self.code
		doc.object_guid = row["objectGUID"]
		doc.distinguished_name = row.get("distinguishedName")
		doc.ou = ou_of(row.get("distinguishedName"))
		doc.when_created = row.get("whenCreated")
		doc.when_changed = row.get("whenChanged")
		doc.missing_in_source = 0

	# ------------------------------------------------------------ groups

	def import_groups(self, groups):
		for row in groups:
			uid = self.key(row["objectGUID"])
			manager = self.user_uid(row.get("managedBy"))
			payload = {
				"g": {k: v for k, v in row.items() if k != "whenChanged"},
				"managed_by": manager,
				"v": DERIVED_VERSION,
			}
			h = src_hash(payload)
			doc = self.load("AD Group", uid, h)
			if doc is None:
				continue
			self.common(doc, row)
			group_type = cint(row.get("groupType"))
			doc.group_name = row.get("cn") or row.get("sAMAccountName")
			doc.sam_account_name = row.get("sAMAccountName")
			doc.description = row.get("description")
			doc.security = int(bool(group_type & GROUP_SECURITY))
			doc.scope = next((label for bit, label in GROUP_SCOPES.items() if group_type & bit), "")
			# the manager account may not be imported yet: link_managers() completes it
			doc.managed_by = manager if manager and frappe.db.exists("AD Account", manager) else None
			doc.src_hash = h
			self.save(doc)
		self.link_parent_groups(groups)

	def link_parent_groups(self, groups):
		"""Nested groups: groups this group is a direct member of (after all groups exist)."""
		names = dict(
			frappe.get_all(
				"AD Group", filters={"domain": self.code}, fields=["name", "group_name"], as_list=True
			)
		)
		current = defaultdict(set)
		for row in frappe.get_all(
			"AD Account Group",
			filters={"parenttype": "AD Group", "parentfield": "parent_groups"},
			fields=["parent", "group"],
			limit_page_length=0,
		):
			current[row.parent].add(row.group)
		for row in groups:
			uid = self.key(row["objectGUID"])
			wanted = {g for g in (self.group_uid(dn) for dn in row.get("memberOf") or []) if g in names}
			if wanted == current.get(uid, set()):
				continue
			doc = frappe.get_doc("AD Group", uid)
			sync_child_table(
				doc,
				"parent_groups",
				("group",),
				[{"group": g, "group_name": names[g]} for g in sorted(wanted)],
			)
			doc.save(ignore_permissions=True, ignore_version=False)
			self.counters["nested_groups_changed"] += 1

	def user_uid(self, dn):
		row = self.user_by_dn.get((dn or "").lower())
		return self.key(row["objectGUID"]) if row else None

	def group_uid(self, dn):
		row = self.group_by_dn.get((dn or "").lower())
		return self.key(row["objectGUID"]) if row else None

	# ------------------------------------------------------------ accounts

	def resolve_person(self, row) -> tuple[str | None, str, str]:
		number = (row.get("employeeNumber") or "").strip().lower()
		if number:
			if number in self.persons:
				return number, BY_EMPLOYEE_NUMBER, ""
			note = f"employeeNumber «{number}» не совпадает ни с одним сотрудником; "
		else:
			note = ""
		full_name = row.get("displayName") or " ".join(
			x for x in (row.get("sn"), row.get("givenName"), row.get("middleName")) if x
		)
		person, name_note = self.names.match(full_name)
		if person:
			return person, BY_NAME, ""
		return None, "", note + name_note

	def import_account(self, row):
		uid = self.key(row["objectGUID"])
		person, method, note = self.resolve_person(row)
		groups = []
		for dn in row.get("memberOf") or []:
			group = self.group_uid(dn)
			if group:
				groups.append(group)
		manager = self.user_uid(row.get("manager"))
		payload = {
			# Last logon and lockout change all the time: kept out of the hash and the history
			"u": {k: v for k, v in row.items() if k not in VOLATILE},
			"person": [person, method, note],
			"groups": sorted(groups),
			"manager": manager,
			"v": DERIVED_VERSION,
		}
		h = src_hash(payload)
		self.volatile[uid] = (row.get("lastLogonTimestamp"), int(bool(row.get("lockoutTime"))))
		doc = self.load("AD Account", uid, h)
		if doc is None:
			return
		self.common(doc, row)
		uac = cint(row.get("userAccountControl"))
		doc.sam_account_name = row.get("sAMAccountName")
		doc.user_principal_name = row.get("userPrincipalName")
		doc.display_name = row.get("displayName") or row.get("sAMAccountName")
		doc.given_name = row.get("givenName")
		doc.surname = row.get("sn")
		doc.mail = row.get("mail")
		doc.title = row.get("title")
		doc.department = row.get("department")
		doc.company = row.get("company")
		doc.employee_number = row.get("employeeNumber")
		doc.employee_id = row.get("employeeID")
		doc.enabled = int(not uac & UAC_DISABLED)
		doc.password_never_expires = int(bool(uac & UAC_DONT_EXPIRE_PASSWORD))
		doc.password_last_set = row.get("pwdLastSet")
		doc.account_expires = row.get("accountExpires")
		doc.person = person
		doc.person_link_method = method
		doc.person_link_note = note
		doc.src_hash = h
		sync_child_table(
			doc,
			"groups",
			("group",),
			[{"group": g, "group_name": self.group_names.get(g, "")} for g in sorted(groups)],
		)
		doc.group_count = len(groups)
		# the manager may be imported later in this run: link_managers() completes it
		doc.manager = manager if manager and frappe.db.exists("AD Account", manager) else None
		if doc.is_new():
			# later they change without a version, see update_volatile()
			last_logon, doc.locked = self.volatile[uid]
			doc.last_logon = get_datetime(last_logon) if last_logon else None
		self.save(doc)

	def link_managers(self, users, groups):
		"""Manager links to accounts created later in the same run (first load)."""
		for doctype, field, rows, source in (
			("AD Account", "manager", users, "manager"),
			("AD Group", "managed_by", groups, "managedBy"),
		):
			for row in rows:
				manager = self.user_uid(row.get(source))
				if not manager:
					continue
				uid = self.key(row["objectGUID"])
				current = frappe.db.get_value(doctype, uid, field)
				if current != manager and frappe.db.exists("AD Account", manager):
					frappe.db.set_value(doctype, uid, field, manager, update_modified=False)

	def update_volatile(self):
		"""Last logon and lockout: written directly, without a version and without touching «modified»."""
		current = {
			r.name: r
			for r in frappe.get_all(
				"AD Account",
				filters={"domain": self.code},
				fields=["name", "last_logon", "locked"],
				limit_page_length=0,
			)
		}
		for uid, (last_logon, locked) in self.volatile.items():
			row = current.get(uid)
			if not row:
				continue
			new_logon = get_datetime(last_logon) if last_logon else None
			if row.last_logon != new_logon or cint(row.locked) != locked:
				frappe.db.set_value(
					"AD Account", uid, {"last_logon": new_logon, "locked": locked}, update_modified=False
				)
				self.counters["last_logon_updated"] += 1

	def mark_missing(self, doctype, seen) -> int:
		count = 0
		for name in frappe.get_all(
			doctype, filters={"domain": self.code, "missing_in_source": 0}, pluck="name"
		):
			if name not in seen:
				doc = frappe.get_doc(doctype, name)
				doc.missing_in_source = 1
				doc.save(ignore_permissions=True, ignore_version=False)
				count += 1
		return count

	def update_group_counts(self):
		counts = dict(
			frappe.db.sql(
				"""select g.`group`, count(*) from `tabAD Account Group` g
				join `tabAD Account` a on a.name = g.parent
				where a.domain = %s and a.missing_in_source = 0 group by g.`group`""",
				self.code,
			)
		)
		for name, current in frappe.get_all(
			"AD Group", filters={"domain": self.code}, fields=["name", "member_count"], as_list=True
		):
			if cint(current) != cint(counts.get(name)):
				frappe.db.set_value(
					"AD Group", name, "member_count", cint(counts.get(name)), update_modified=False
				)


def relink_ib_users() -> int:
	"""After an AD load: 1C users get their AD account and, through it, the employee."""
	index = ad_account_index()
	changed = 0
	for user in frappe.get_all(
		"IB User",
		filters={"ad_login": ["is", "set"]},
		fields=["name", "ad_domain", "ad_login", "ad_account", "person", "person_link_method"],
		limit_page_length=0,
	):
		account, ad_person = index.get(
			((user.ad_domain or "").lower(), (user.ad_login or "").lower()), (None, None)
		)
		updates = {}
		if (user.ad_account or None) != account:
			updates["ad_account"] = account
		# GUID (ZUP) and manual links stay; AD beats the full-name guess
		if user.person_link_method in ("", None, BY_NAME, BY_AD) and ad_person and user.person != ad_person:
			updates.update({"person": ad_person, "person_link_method": BY_AD, "person_link_note": ""})
		if updates:
			doc = frappe.get_doc("IB User", user.name)
			doc.update(updates)
			doc.save(ignore_permissions=True, ignore_version=False)
			changed += 1
	return changed


def logon_age_days(value) -> int | None:
	if not value:
		return None
	return (now_datetime() - get_datetime(value)).days
